version: 2.1

jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run tslint
      - run: yarn run prettier --list-different

workflows:
  check:
    jobs:
      - check:
          filters:
            branches:
              ignore: master
